import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
        <div className="h-screen overflow-hidden">
          <aside className="fixed top-0 left-0 h-screen w-64 border-r bg-background/60">
            <Sidebar />
          </aside>
          <div className="ml-64 h-screen overflow-y-auto relative">
            <main className="min-h-screen p-8">{children}</main>
            {/* Modal slot overlays via portal; keep after children */}
            {modal}
          </div>
        </div>
      </body>
    </html>
  );
}
